Update mail.yaml

diff --git a/.github/workflows/mail.yaml b/.github/workflows/mail.yaml
--- a/.github/workflows/mail.yaml
+++ b/.github/workflows/mail.yaml
@@ -3,31 +3,58 @@ on:
   schedule:
     - cron: "0 0 * * 0"
   workflow_dispatch:
+
 jobs:
   Update:
     runs-on: ubuntu-latest
     steps:
     - name: Clone Repository
       uses: actions/checkout@main
-    - name: Download Core
+
+    - name: Download Clash Core
       run: |
-        download_file_name=$(wget -O - "https://api.github.com/repos/Dreamacro/clash/releases/tags/premium" 2> /dev/null | jq ".assets[].name" | grep -m 1 "linux-arm64" | xargs)
-        if [[ -z "$download_file_name" ]]; then
+        clash_download_file_name=$(wget -O - "https://api.github.com/repos/Dreamacro/clash/releases/tags/premium" 2> /dev/null | jq -r ".assets[] | select(.name | test(\"linux-arm64\")) | .name" | grep -m 1 ".gz")
+        if [[ -z "$clash_download_file_name" ]]; then
           echo -n "Unable to list clash files."
           exit 1
         fi
-        echo "Filename: $download_file_name"
-        ver="${download_file_name%.*}"
-        mkdir -p /tmp/core/$ver
+        echo "Filename: $clash_download_file_name"
+        clash_ver="${clash_download_file_name%.*.*}"
+        mkdir -p /tmp/core/clash/$clash_ver
+        wget "https://github.com/Dreamacro/clash/releases/download/premium/${clash_download_file_name}" -q --show-progress -O /tmp/core/clash/$clash_ver/clash.gz
+        echo "$clash_ver" > /tmp/core/clash/clash_binary_lastest.txt
+        gzip -d -f /tmp/core/clash/$clash_ver/clash.gz
+        md5sum /tmp/core/clash/$clash_ver/clash | awk '{print $1}' | tr a-z A-Z > /tmp/core/clash/$clash_ver/md5sum.txt
+
+
+    - name: Download Mihomo Core
+      run: |
+        mihomo_download_file_name=$(wget -O - "https://api.github.com/repos/MetaCubeX/mihomo/releases/latest" 2> /dev/null | jq -r ".assets[] | select(.name | test(\"linux-arm64\")) | .name" | grep -m 1 ".gz")
+        if [[ -z "$mihomo_download_file_name" ]]; then
+          echo -n "Unable to list mihomo files."
+          exit 1
+        fi
+        echo "Filename: $mihomo_download_file_name"
+        mihomo_ver="${mihomo_download_file_name%.*.*}"
+        mkdir -p /tmp/coremeta/mihomo/$mihomo_ver
+        wget "https://github.com/MetaCubeX/mihomo/releases/download/${mihomo_ver}/${mihomo_download_file_name}" -q --show-progress -O /tmp/coremeta/mihomo/$mihomo_ver/mihomo.gz
+        echo "$mihomo_ver" > /tmp/coremeta/mihomo/mihomo_binary_lastest.txt
+        gzip -d -f /tmp/coremeta/mihomo/$mihomo_ver/mihomo.gz
+        md5sum /tmp/coremeta/mihomo/$mihomo_ver/mihomo | awk '{print $1}' | tr a-z A-Z > /tmp/coremeta/mihomo/$mihomo_ver/md5sum.txt
+
+    - name: Copy Files to Core and Coremeta
+      run: |
         mkdir -p core
-        wget "https://github.com/Dreamacro/clash/releases/download/premium/$download_file_name" -q --show-progress -O /tmp/core/$ver/clash.gz
-        echo "$ver" > /tmp/core/clash_binary_lastest.txt
-        gzip -d -f /tmp/core/$ver/clash.gz
-        md5sum /tmp/core/$ver/clash |awk '{print $1}' | tr a-z A-Z > /tmp/core/$ver/md5sum.txt
+        mkdir -p coremeta
         cp -rfa /tmp/core/* core
+        cp -rfa /tmp/coremeta/* coremeta
         rm -fr /tmp/core
+        rm -fr /tmp/coremeta
+
+    - name: Commit and Push
+      run: |
         git init
         git config --local user.name "github-actions[bot]"
         git config --local user.email "github-actions[bot]@users.noreply.github.com"
-        git add . && git commit -m "Update Core to ${ver}" || exit 0
+        git add . && git commit -m "Update Clash Core to ${clash_ver} and Mihomo Core to ${mihomo_ver}" || exit 0
         git push
